const http=require('http');
const originalEnd=http.ServerResponse.prototype.end;
const injection=`<style>
#elo-live-bell{position:fixed;right:22px;top:22px;z-index:9999;border:1px solid #303541;background:#111319;color:#fff;border-radius:12px;padding:10px 13px;cursor:pointer;box-shadow:0 10px 35px #0008}#elo-live-bell span{display:inline-flex;min-width:18px;height:18px;align-items:center;justify-content:center;border-radius:99px;background:#fff;color:#000;font-size:11px;font-weight:800;margin-left:5px}.elo-live-panel{position:fixed;right:22px;top:68px;width:min(380px,calc(100vw - 44px));z-index:9998;background:#111319;border:1px solid #303541;border-radius:15px;padding:14px;box-shadow:0 20px 60px #0009}.elo-live-item{padding:10px;border:1px solid #292e38;border-radius:10px;margin:7px 0}.elo-ticket-chat{margin-top:10px;border:1px solid #303541;border-radius:12px;padding:10px;background:#090b0f}.elo-ticket-messages{max-height:260px;overflow:auto}.elo-ticket-msg{padding:8px 10px;border-radius:10px;background:#1b1f28;margin:7px 0}.elo-ticket-msg.me{background:#fff;color:#08090c;margin-left:15%}.elo-ticket-compose{display:flex;gap:7px;margin-top:8px}.elo-ticket-compose input{flex:1!important}.elo-ticket-compose button{width:auto!important}.elo-chat-open{margin-top:8px!important;width:auto!important}
</style><button id="elo-live-bell" class="hidden">🔔 <span id="elo-live-count">0</span></button><div id="elo-live-panel" class="elo-live-panel hidden"><b>Notificações</b><div id="elo-live-items"></div></div><script>
(function(){
 if(!location.pathname.endsWith('/conta.html'))return;
 const wait=()=>{if(typeof window.api!=='function')return setTimeout(wait,100);const bell=document.getElementById('elo-live-bell'),panel=document.getElementById('elo-live-panel'),count=document.getElementById('elo-live-count'),items=document.getElementById('elo-live-items');if(!bell)return;let currentTicket=null,lastUnread=-1;bell.classList.remove('hidden');bell.onclick=()=>panel.classList.toggle('hidden');
 function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));}
 function brlText(){document.body.innerHTML=document.body.innerHTML.replace(/€\s*/g,'R$ ');}
 async function notifications(){try{const d=await window.api('/api/account/notifications');const unread=d.filter(n=>!n.read);count.textContent=unread.length;count.style.display=unread.length?'inline-flex':'none';items.innerHTML=d.length?d.slice(0,8).map(n=>'<div class="elo-live-item"><b>'+esc(n.title)+'</b><br>'+esc(n.message)+'<br><small>'+esc(n.created_at)+'</small></div>').join(''):'<div class="muted" style="margin-top:10px">Sem notificações.</div>';if(unread.length>lastUnread&&lastUnread>=0&&unread.length>0)panel.classList.remove('hidden');lastUnread=unread.length;}catch{}}
 async function tickets(){try{const d=await window.api('/api/account/tickets');const list=document.getElementById('ticketsList');if(!list)return;list.innerHTML=d.length?d.map(t=>'<div class="item" data-ticket-id="'+t.id+'"><div class="row"><b>'+esc(t.ticket_number)+'</b><span class="badge">'+esc(t.status)+'</span></div><p><b>'+esc(t.subject)+'</b></p><span class="muted small">'+esc(t.message)+'</span><br><button class="btn dark elo-chat-open">💬 Abrir chat</button><div class="elo-ticket-chat hidden"><div class="elo-ticket-messages"></div><div class="elo-ticket-compose"><input placeholder="Escreve uma mensagem..."><button class="btn">Enviar</button></div></div></div>').join(''):'<div class="empty">Ainda não tens tickets.</div>';list.querySelectorAll('[data-ticket-id]').forEach(box=>{const id=Number(box.dataset.ticketId),btn=box.querySelector('.elo-chat-open'),chat=box.querySelector('.elo-ticket-chat');btn.onclick=async()=>{chat.classList.toggle('hidden');if(!chat.classList.contains('hidden')){currentTicket=id;await loadChat(id,chat);}};chat.querySelector('button').onclick=async()=>{const input=chat.querySelector('input'),message=input.value.trim();if(!message)return;try{await window.api('/api/account/tickets/'+id+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});input.value='';await loadChat(id,chat);}catch(e){alert(e.message)}};});}catch{}}
 async function loadChat(id,box){try{const d=await window.api('/api/account/tickets/'+id+'/messages');box.querySelector('.elo-ticket-messages').innerHTML=d.map(m=>'<div class="elo-ticket-msg '+(m.sender_type==='cliente'?'me':'')+'"><b>'+(m.sender_type==='cliente'?'Tu':'Elo Store')+'</b><br>'+esc(m.message)+'<br><small>'+esc(m.created_at)+'</small></div>').join('')||'<span class="muted">Sem mensagens.</span>';const el=box.querySelector('.elo-ticket-messages');el.scrollTop=el.scrollHeight;}catch(e){box.querySelector('.elo-ticket-messages').textContent=e.message}}
 async function refresh(){brlText();await notifications();await tickets();brlText();}
 refresh();setInterval(refresh,8000);};wait();
})();
</script>`;
http.ServerResponse.prototype.end=function(chunk,encoding,callback){let text=null;if(typeof chunk==='string')text=chunk;else if(Buffer.isBuffer(chunk))text=chunk.toString('utf8');if(text&&text.includes('<body')&&text.includes('eloCustomer')&&text.includes('Minha Conta')){text=text.replace('</body>',injection+'</body>');chunk=typeof chunk==='string'?text:Buffer.from(text,'utf8');}return originalEnd.call(this,chunk,encoding,callback);};
console.log('Customer UI hook: notifications, ticket chat and BRL display active.');