const http=require('http');
const originalEnd=http.ServerResponse.prototype.end;
const injection=`<style>
#elo-live-bell{position:fixed;right:22px;top:22px;z-index:9999;border:1px solid #303541;background:#111319;color:#fff;border-radius:12px;padding:10px 13px;cursor:pointer;box-shadow:0 10px 35px #0008}#elo-live-bell span{display:inline-flex;min-width:18px;height:18px;align-items:center;justify-content:center;border-radius:99px;background:#fff;color:#000;font-size:11px;font-weight:800;margin-left:5px}.elo-live-panel{position:fixed;right:22px;top:68px;width:min(380px,calc(100vw - 44px));z-index:9998;background:#111319;border:1px solid #303541;border-radius:15px;padding:14px;box-shadow:0 20px 60px #0009}.elo-live-item{padding:10px;border:1px solid #292e38;border-radius:10px;margin:7px 0}.elo-ticket-chat{margin-top:10px;border:1px solid #303541;border-radius:12px;padding:10px;background:#090b0f}.elo-ticket-messages{max-height:260px;overflow:auto}.elo-ticket-msg{padding:8px 10px;border-radius:10px;background:#1b1f28;margin:7px 0}.elo-ticket-msg.me{background:#fff;color:#08090c;margin-left:15%}.elo-ticket-compose{display:flex;gap:7px;margin-top:8px}.elo-ticket-compose input{flex:1!important}.elo-ticket-compose button{width:auto!important}.elo-chat-open{margin-top:8px!important;width:auto!important}
</style><button id="elo-live-bell" class="hidden">🔔 <span id="elo-live-count">0</span></button><div id="elo-live-panel" class="elo-live-panel hidden"><b>Notificações</b><div id="elo-live-items"></div></div><script>
(function(){
 if(!location.pathname.endsWith('/conta.html'))return;
 const wait=()=>{if(typeof window.api!=='function'||typeof window.render!=='function')return setTimeout(wait,100);
   const bell=document.getElementById('elo-live-bell'),panel=document.getElementById('elo-live-panel'),count=document.getElementById('elo-live-count'),items=document.getElementById('elo-live-items');
   if(!bell)return;
   let currentTicket=null,lastSeen=0;
   bell.classList.remove('hidden');
   bell.onclick=()=>panel.classList.toggle('hidden');
   async function notifications(){try{const d=await window.api('/api/account/notifications');const unread=d.filter(n=>!n.read);count.textContent=unread.length;count.style.display=unread.length?'inline-flex':'none';items.innerHTML=d.length?d.slice(0,8).map(n=>'<div class="elo-live-item"><b>'+esc(n.title)+'</b><br>'+esc(n.message)+'<br><small>'+esc(n.created_at)+'</small></div>').join(''):'<div class="muted" style="margin-top:10px">Sem notificações.</div>';if(unread.length>lastSeen&&lastSeen!==0){panel.classList.remove('hidden');}lastSeen=unread.length;}catch{}}
   async function chat(id,box){try{const d=await window.api('/api/account/tickets/'+id+'/messages');box.querySelector('.elo-ticket-messages').innerHTML=d.map(m=>'<div class="elo-ticket-msg '+(m.sender_type==='cliente'?'me':'')+'"><b>'+(m.sender_type==='cliente'?'Tu':'Elo Store')+'</b><br>'+esc(m.message)+'<br><small>'+esc(m.created_at)+'</small></div>').join('')||'<span class="muted">Sem mensagens.</span>';const el=box.querySelector('.elo-ticket-messages');el.scrollTop=el.scrollHeight;}catch(e){box.querySelector('.elo-ticket-messages').textContent=e.message}}
   function addChats(){const list=document.getElementById('ticketsList');if(!list)return;list.querySelectorAll('.item').forEach((item,i)=>{if(item.querySelector('.elo-chat-open'))return;const t=(window.state&&window.state.tickets||[])[i];if(!t)return;const btn=document.createElement('button');btn.className='btn dark elo-chat-open';btn.textContent='💬 Abrir chat';const box=document.createElement('div');box.className='elo-ticket-chat hidden';box.innerHTML='<div class="elo-ticket-messages"></div><div class="elo-ticket-compose"><input placeholder="Escreve uma mensagem..."><button class="btn">Enviar</button></div>';item.appendChild(btn);item.appendChild(box);btn.onclick=async()=>{box.classList.toggle('hidden');if(!box.classList.contains('hidden')){currentTicket=t.id;await chat(t.id,box);}};box.querySelector('button').onclick=async()=>{const input=box.querySelector('input'),message=input.value.trim();if(!message)return;try{await window.api('/api/account/tickets/'+t.id+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});input.value='';await chat(t.id,box);}catch(e){alert(e.message)}};});}
   const originalRender=window.render;window.render=function(){originalRender();setTimeout(addChats,0);};
   setInterval(async()=>{await notifications();if(currentTicket){const item=(window.state.tickets||[]).find(x=>x.id===currentTicket);if(item){const box=[...document.querySelectorAll('.elo-ticket-chat')].find(x=>x.querySelector('.elo-ticket-messages')&&x.closest('.item'));if(box&&!box.classList.contains('hidden'))await chat(currentTicket,box);}}},10000);
   notifications();setTimeout(addChats,200);function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));}
 };wait();
})();
</script>`;
http.ServerResponse.prototype.end=function(chunk,encoding,callback){if(typeof chunk==='string'&&chunk.includes('<body')&&chunk.includes('eloCustomer')&&chunk.includes('Minha Conta'))chunk=chunk.replace('</body>',injection+'</body>');return originalEnd.call(this,chunk,encoding,callback);};
console.log('Customer UI hook: live notifications and ticket chat active.');